name: users_comments
description: A new Flutter application.




version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.2
  hive: ^1.4.2
  hive_flutter: ^0.3.1
  path_provider: ^1.6.11



dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.7.1
  build_runner:


flutter:


  uses-material-design: true

