name: users_comments
description: A new Flutter application.




version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter




dev_dependencies:
  flutter_test:
    sdk: flutter
  http: ^0.12.2

flutter:


  uses-material-design: true

